// [TRANSLATION_NOTE]: ConstEnums.h -> Rust 枚举
// C++ 的 int32_t 枚举映射为 Rust 的 #[repr(i32)] 枚举

#![allow(non_camel_case_types, dead_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum AdviceType {
    ADVICE_NONE = -1,
    ADVICE_CLICK_ON_SUN = 0,
    ADVICE_CLICKED_ON_SUN = 1,
    ADVICE_CLICKED_ON_COIN = 2,
    ADVICE_SEED_REFRESH = 3,
    ADVICE_CANT_AFFORD_PLANT = 4,
    ADVICE_PLANT_GRAVEBUSTERS_ON_GRAVES = 5,
    ADVICE_PLANT_LILYPAD_ON_WATER = 6,
    ADVICE_PLANT_TANGLEKELP_ON_WATER = 7,
    ADVICE_PLANT_SEASHROOM_ON_WATER = 8,
    ADVICE_PLANT_POTATOE_MINE_ON_LILY = 9,
    ADVICE_PLANT_WRONG_ART_TYPE = 10,
    ADVICE_PLANT_NEED_POT = 11,
    ADVICE_PLANT_NOT_ON_GRAVE = 12,
    ADVICE_PLANT_NOT_ON_CRATER = 13,
    ADVICE_CANT_PLANT_THERE = 14,
    ADVICE_PLANT_NOT_ON_WATER = 15,
    ADVICE_PLANTING_NEEDS_GROUND = 16,
    ADVICE_BEGHOULED_DRAG_TO_MATCH_3 = 17,
    ADVICE_BEGHOULED_MATCH_3 = 18,
    ADVICE_BEGHOULED_MATCH_4 = 19,
    ADVICE_BEGHOULED_SAVE_SUN = 20,
    ADVICE_BEGHOULED_USE_CRATER_1 = 21,
    ADVICE_BEGHOULED_USE_CRATER_2 = 22,
    ADVICE_PLANT_NOT_PASSED_LINE = 23,
    ADVICE_PLANT_ONLY_ON_REPEATERS = 24,
    ADVICE_PLANT_ONLY_ON_MELONPULT = 25,
    ADVICE_PLANT_ONLY_ON_SUNFLOWER = 26,
    ADVICE_PLANT_ONLY_ON_SPIKEWEED = 27,
    ADVICE_PLANT_ONLY_ON_KERNELPULT = 28,
    ADVICE_PLANT_ONLY_ON_MAGNETSHROOM = 29,
    ADVICE_PLANT_ONLY_ON_FUMESHROOM = 30,
    ADVICE_PLANT_ONLY_ON_LILYPAD = 31,
    ADVICE_PLANT_NEEDS_REPEATER = 32,
    ADVICE_PLANT_NEEDS_MELONPULT = 33,
    ADVICE_PLANT_NEEDS_SUNFLOWER = 34,
    ADVICE_PLANT_NEEDS_SPIKEWEED = 35,
    ADVICE_PLANT_NEEDS_KERNELPULT = 36,
    ADVICE_PLANT_NEEDS_MAGNETSHROOM = 37,
    ADVICE_PLANT_NEEDS_FUMESHROOM = 38,
    ADVICE_PLANT_NEEDS_LILYPAD = 39,
    ADVICE_SLOT_MACHINE_PULL = 40,
    ADVICE_HUGE_WAVE = 41,
    ADVICE_SHOVEL_REFRESH = 42,
    ADVICE_PORTAL_RELOCATING = 43,
    ADVICE_SLOT_MACHINE_COLLECT_SUN = 44,
    ADVICE_DESTORY_POTS_TO_FINISIH_LEVEL = 45,
    ADVICE_USE_SHOVEL_ON_POTS = 46,
    ADVICE_ALMOST_THERE = 47,
    ADVICE_ZOMBIQUARIUM_CLICK_TROPHY = 48,
    ADVICE_ZOMBIQUARIUM_COLLECT_SUN = 49,
    ADVICE_ZOMBIQUARIUM_CLICK_TO_FEED,
    ADVICE_ZOMBIQUARIUM_BUY_SNORKEL,
    ADVICE_I_ZOMBIE_PLANTS_NOT_REAL,
    ADVICE_I_ZOMBIE_NOT_PASSED_LINE,
    ADVICE_I_ZOMBIE_LEFT_OF_LINE,
    ADVICE_SLOT_MACHINE_SPIN_AGAIN,
    ADVICE_I_ZOMBIE_EAT_ALL_BRAINS,
    ADVICE_PEASHOOTER_DIED,
    ADVICE_STINKY_SLEEPING,
    ADVICE_BEGHOULED_NO_MOVES,
    ADVICE_PLANT_SUNFLOWER5,
    ADVICE_PLANTING_NEED_SLEEPING,
    ADVICE_CLICK_TO_CONTINUE,
    ADVICE_SURVIVE_FLAGS,
    ADVICE_UNLOCKED_MODE,
    ADVICE_NEED_WHEELBARROW,
    NUM_ADVICE_TYPES,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum AlmanacPage {
    ALMANAC_PAGE_INDEX,
    ALMANAC_PAGE_PLANTS,
    ALMANAC_PAGE_ZOMBIES,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum AwardType {
    AWARD_FORLEVEL,
    AWARD_CREDITS_ZOMBIENOTE,
    AWARD_HELP_ZOMBIENOTE,
    AWARD_ACHIEVEMENTONLY,
    AWARD_PRECREDITS_ZOMBIENOTE,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum BackgroundType {
    BACKGROUND_1_DAY,
    BACKGROUND_2_NIGHT,
    BACKGROUND_3_POOL,
    BACKGROUND_4_FOG,
    BACKGROUND_5_ROOF,
    BACKGROUND_6_BOSS,
    BACKGROUND_MUSHROOM_GARDEN,
    BACKGROUND_GREENHOUSE,
    BACKGROUND_ZOMBIQUARIUM,
    BACKGROUND_TREEOFWISDOM,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum BoardResult {
    BOARDRESULT_NONE = 0,
    BOARDRESULT_WON = 1,
    BOARDRESULT_LOST = 2,
    BOARDRESULT_RESTART = 3,
    BOARDRESULT_QUIT = 4,
    BOARDRESULT_QUIT_APP = 5,
    BOARDRESULT_CHEAT = 6,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum BossPart {
    BOSS_PART_BACK_LEG = 0,
    BOSS_PART_FRONT_LEG = 1,
    BOSS_PART_MAIN = 2,
    BOSS_PART_BACK_ARM = 3,
    BOSS_PART_FIREBALL = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ChallengePage {
    CHALLENGE_PAGE_SURVIVAL = 0,
    CHALLENGE_PAGE_CHALLENGE = 1,
    CHALLENGE_PAGE_LIMBO = 2,
    CHALLENGE_PAGE_PUZZLE = 3,
    MAX_CHALLANGE_PAGES = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ChallengeState {
    STATECHALLENGE_NORMAL,
    STATECHALLENGE_BEGHOULED_MOVING,
    STATECHALLENGE_BEGHOULED_FALLING,
    STATECHALLENGE_BEGHOULED_NO_MATCHES,
    STATECHALLENGE_SLOT_MACHINE_ROLLING,
    STATECHALLENGE_STORM_FLASH_1,
    STATECHALLENGE_STORM_FLASH_2,
    STATECHALLENGE_STORM_FLASH_3,
    STATECHALLENGE_ZEN_FADING,
    STATECHALLENGE_SCARY_POTTER_MALLETING,
    STATECHALLENGE_LAST_STAND_ONSLAUGHT,
    STATECHALLENGE_TREE_JUST_GREW,
    STATECHALLENGE_TREE_GIVE_WISDOM,
    STATECHALLENGE_TREE_WAITING_TO_BABBLE,
    STATECHALLENGE_TREE_BABBLING,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ChosenSeedState {
    SEED_FLYING_TO_BANK = 0,
    SEED_IN_BANK = 1,
    SEED_FLYING_TO_CHOOSER = 2,
    SEED_IN_CHOOSER = 3,
    SEED_PACKET_HIDDEN = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum CoinMotion {
    COIN_MOTION_FROM_SKY = 0,
    COIN_MOTION_FROM_SKY_SLOW = 1,
    COIN_MOTION_FROM_PLANT = 2,
    COIN_MOTION_COIN = 3,
    COIN_MOTION_LAWNMOWER_COIN = 4,
    COIN_MOTION_FROM_PRESENT = 5,
    COIN_MOTION_FROM_BOSS = 6,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum CoinType {
    COIN_NONE,
    COIN_SILVER,
    COIN_GOLD,
    COIN_DIAMOND,
    COIN_SUN,
    COIN_SMALLSUN,
    COIN_LARGESUN,
    COIN_FINAL_SEED_PACKET,
    COIN_TROPHY,
    COIN_SHOVEL,
    COIN_ALMANAC,
    COIN_CARKEYS,
    COIN_VASE,
    COIN_WATERING_CAN,
    COIN_TACO,
    COIN_NOTE,
    COIN_USABLE_SEED_PACKET,
    COIN_PRESENT_PLANT,
    COIN_AWARD_MONEY_BAG,
    COIN_AWARD_PRESENT,
    COIN_AWARD_BAG_DIAMOND,
    COIN_AWARD_SILVER_SUNFLOWER,
    COIN_AWARD_GOLD_SUNFLOWER,
    COIN_CHOCOLATE,
    COIN_AWARD_CHOCOLATE,
    COIN_PRESENT_MINIGAMES,
    COIN_PRESENT_PUZZLE_MODE,
    COIN_PRESENT_SURVIVAL_MODE,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum CrazyDaveState {
    CRAZY_DAVE_OFF = 0,
    CRAZY_DAVE_ENTERING = 1,
    CRAZY_DAVE_LEAVING = 2,
    CRAZY_DAVE_IDLING = 3,
    CRAZY_DAVE_TALKING = 4,
    CRAZY_DAVE_HANDING_TALKING = 5,
    CRAZY_DAVE_HANDING_IDLING = 6,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum CursorType {
    CURSOR_TYPE_NORMAL,
    CURSOR_TYPE_PLANT_FROM_BANK,
    CURSOR_TYPE_PLANT_FROM_USABLE_COIN,
    CURSOR_TYPE_PLANT_FROM_GLOVE,
    CURSOR_TYPE_PLANT_FROM_DUPLICATOR,
    CURSOR_TYPE_PLANT_FROM_WHEEL_BARROW,
    CURSOR_TYPE_SHOVEL,
    CURSOR_TYPE_HAMMER,
    CURSOR_TYPE_COBCANNON_TARGET,
    CURSOR_TYPE_WATERING_CAN,
    CURSOR_TYPE_FERTILIZER,
    CURSOR_TYPE_BUG_SPRAY,
    CURSOR_TYPE_PHONOGRAPH,
    CURSOR_TYPE_CHOCOLATE,
    CURSOR_TYPE_GLOVE,
    CURSOR_TYPE_MONEY_SIGN,
    CURSOR_TYPE_WHEEELBARROW,
    CURSOR_TYPE_TREE_FOOD,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum DamageFlags {
    DAMAGE_BYPASSES_SHIELD = 0,
    DAMAGE_HITS_SHIELD_AND_BODY = 1,
    DAMAGE_FREEZE = 2,
    DAMAGE_DOESNT_CAUSE_FLASH = 3,
    DAMAGE_DOESNT_LEAVE_BODY = 4,
    DAMAGE_SPIKE = 5,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum DamageRangeFlags {
    DAMAGES_GROUND,
    DAMAGES_FLYING,
    DAMAGES_SUBMERGED,
    DAMAGES_DOG,
    DAMAGES_OFF_GROUND,
    DAMAGES_DYING,
    DAMAGES_UNDERGROUND,
    DAMAGES_ONLY_MINDCONTROLLED,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum Dialogs {
    DIALOG_NEW_GAME,
    DIALOG_OPTIONS,
    DIALOG_NEWOPTIONS,
    DIALOG_ALMANAC,
    DIALOG_STORE,
    DIALOG_PREGAME_NAG,
    DIALOG_LOAD_GAME,
    DIALOG_CONFIRM_UPDATE_CHECK,
    DIALOG_CHECKING_UPDATES,
    DIALOG_REGISTER_ERROR,
    DIALOG_COLORDEPTH_EXP,
    DIALOG_OPENURL_WAIT,
    DIALOG_OPENURL_FAIL,
    DIALOG_QUIT,
    DIALOG_HIGH_SCORES,
    DIALOG_NAG,
    DIALOG_INFO,
    DIALOG_GAME_OVER,
    DIALOG_LEVEL_COMPLETE,
    DIALOG_PAUSED,
    DIALOG_NO_MORE_MONEY,
    DIALOG_BONUS,
    DIALOG_CONFIRM_BACK_TO_MAIN,
    DIALOG_CONFIRM_RESTART,
    DIALOG_THANKS_FOR_REGISTERING,
    DIALOG_NOT_ENOUGH_MONEY,
    DIALOG_UPGRADED,
    DIALOG_NO_UPGRADE,
    DIALOG_CHOOSER_WARNING,
    DIALOG_USERDIALOG,
    DIALOG_CREATEUSER,
    DIALOG_CONFIRMDELETEUSER,
    DIALOG_RENAMEUSER,
    DIALOG_CREATEUSERERROR,
    DIALOG_RENAMEUSERERROR,
    DIALOG_CHEAT,
    DIALOG_CHEATERROR,
    DIALOG_CONTINUE,
    DIALOG_GETREADY,
    DIALOG_RESTARTCONFIRM,
    DIALOG_CONFIRMPURCHASE,
    DIALOG_CONFIRMSELL,
    DIALOG_TIMESUP,
    DIALOG_VIRTUALHELP,
    DIALOG_JUMPAHEAD,
    DIALOG_CRAZY_DAVE,
    DIALOG_STORE_PURCHASE,
    DIALOG_ZEN_SELL,
    DIALOG_MESSAGE,
    DIALOG_IMITATER,
    DIALOG_PURCHASE_PACKET_SLOT,
    DIALOG_ZOMBATAR_TOS,
    DIALOG_ZOMBATAR_DELETE,
    NUM_DIALOGS,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum DebugTextMode {
    DEBUG_TEXT_NONE = 0,
    DEBUG_TEXT_ZOMBIE_SPAWN = 1,
    DEBUG_TEXT_MUSIC = 2,
    DEBUG_TEXT_MEMORY = 3,
    DEBUG_TEXT_COLLISION = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum DrawStringJustification {
    DS_ALIGN_LEFT = 0,
    DS_ALIGN_RIGHT = 1,
    DS_ALIGN_CENTER = 2,
    DS_ALIGN_LEFT_VERTICAL_MIDDLE = 3,
    DS_ALIGN_RIGHT_VERTICAL_MIDDLE = 4,
    DS_ALIGN_CENTER_VERTICAL_MIDDLE = 5,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum DrawVariation {
    VARIATION_NORMAL,
    VARIATION_IMITATER,
    VARIATION_MARIGOLD_WHITE,
    VARIATION_MARIGOLD_MAGENTA,
    VARIATION_MARIGOLD_ORANGE,
    VARIATION_MARIGOLD_PINK,
    VARIATION_MARIGOLD_LIGHT_BLUE,
    VARIATION_MARIGOLD_RED,
    VARIATION_MARIGOLD_BLUE,
    VARIATION_MARIGOLD_VIOLET,
    VARIATION_MARIGOLD_LAVENDER,
    VARIATION_MARIGOLD_YELLOW,
    VARIATION_MARIGOLD_LIGHT_GREEN,
    VARIATION_ZEN_GARDEN,
    VARIATION_ZEN_GARDEN_WATER,
    VARIATION_SPROUT_NO_FLOWER,
    VARIATION_IMITATER_LESS,
    VARIATION_AQUARIUM,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum EffectType {
    EFFECT_PARTICLE = 0,
    EFFECT_TRAIL = 1,
    EFFECT_REANIM = 2,
    EFFECT_ATTACHMENT = 3,
    EFFECT_OTHER = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum EmitterType {
    EMITTER_CIRCLE = 0,
    EMITTER_BOX = 1,
    EMITTER_BOX_PATH = 2,
    EMITTER_CIRCLE_PATH = 3,
    EMITTER_CIRCLE_EVEN_SPACING = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GameMode {
    GAMEMODE_ADVENTURE,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_1,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_2,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_3,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_4,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_5,
    GAMEMODE_SURVIVAL_HARD_STAGE_1,
    GAMEMODE_SURVIVAL_HARD_STAGE_2,
    GAMEMODE_SURVIVAL_HARD_STAGE_3,
    GAMEMODE_SURVIVAL_HARD_STAGE_4,
    GAMEMODE_SURVIVAL_HARD_STAGE_5,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_1,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_2,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_3,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_4,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_5,
    GAMEMODE_CHALLENGE_WAR_AND_PEAS,
    GAMEMODE_CHALLENGE_WALLNUT_BOWLING,
    GAMEMODE_CHALLENGE_SLOT_MACHINE,
    GAMEMODE_CHALLENGE_RAINING_SEEDS,
    GAMEMODE_CHALLENGE_BEGHOULED,
    GAMEMODE_CHALLENGE_INVISIGHOUL,
    GAMEMODE_CHALLENGE_BOBSLED_BONANZA,
    GAMEMODE_CHALLENGE_ZOMBIE_NIMBLE_ZOMBIE_QUICK,
    GAMEMODE_CHALLENGE_WHACK_A_ZOMBIE,
    GAMEMODE_CHALLENGE_LITTLE_TROUBLE,
    GAMEMODE_CHALLENGE_PORTAL_COMBAT,
    GAMEMODE_CHALLENGE_COLUMN,
    GAMEMODE_CHALLENGE_POGO_PARTY,
    GAMEMODE_CHALLENGE_WALLNUT_BOWLING_2,
    GAMEMODE_CHALLENGE_ZOMBIES_ON_THE_ROCKS,
    GAMEMODE_CHALLENGE_RAINING_SEEDS_2,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_1,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_2,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_3,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_4,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_5,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_6,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_7,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_8,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_9,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_10,
    GAMEMODE_CHALLENGE_PUZZLE_I_ZOMBIE_ENDLESS,
    GAMEMODE_SCARY_POTTER_1,
    GAMEMODE_SCARY_POTTER_2,
    GAMEMODE_SCARY_POTTER_3,
    GAMEMODE_SCARY_POTTER_4,
    GAMEMODE_SCARY_POTTER_5,
    GAMEMODE_SCARY_POTTER_6,
    GAMEMODE_SCARY_POTTER_7,
    GAMEMODE_SCARY_POTTER_8,
    GAMEMODE_SCARY_POTTER_9,
    GAMEMODE_SCARY_POTTER_10,
    GAMEMODE_SCARY_POTTER_ENDLESS,
    GAMEMODE_PUZZLE_ZEN_GARDEN,
    GAMEMODE_TREE_OF_WISDOM,
    GAMEMODE_ZOMBIQUARIUM,
    GAMEMODE_TWO_PLAYER_VERSUS,
    GAMEMODE_TWO_PLAYER_COOP,
    NUM_GAME_MODES,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GameScenes {
    SCENE_LOADING = 0,
    SCENE_MENU = 1,
    SCENE_LEVEL_INTRO = 2,
    SCENE_PLAYING = 3,
    SCENE_ZOMBIES_WON = 4,
    SCENE_AWARD = 5,
    SCENE_CREDIT = 6,
    SCENE_CHALLENGE = 7,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GardenType {
    GARDEN_MAIN = 0,
    GARDEN_MUSHROOM = 1,
    GARDEN_WHEELBARROW = 2,
    GARDEN_AQUARIUM = 3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GridItemType {
    GRIDITEM_NONE,
    GRIDITEM_SCREEN_DOOR,
    GRIDITEM_LADDER,
    GRIDITEM_RAKE,
    GRIDITEM_STONE_WALL,
    GRIDITEM_TINY_URAN,
    GRIDITEM_CRATER,
    GRIDITEM_BRAIN,
    GRIDITEM_PORTAL_CIRCLE,
    GRIDITEM_SQUASH_ZOMBIE,
    GRIDITEM_ZEN_TOOL,
    GRIDITEM_TREE,
    GRIDITEM_BOSS_HEAD,
    GRIDITEM_BOSS_DRIVER,
    GRIDITEM_TV,
    GRIDITEM_ZOMBIQUARIUM,
    NUM_GRIDITEMS,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum HitResult {
    HIT_RESULT_NONE = -1,
    HIT_RESULT_SKIP = 0,
    HIT_RESULT_NORMAL = 1,
    HIT_RESULT_POP = 2,
    HIT_RESULT_SHOW = 3,
    HIT_RESULT_KILLED = 4,
    HIT_RESULT_BOUNCE = 5,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum HolderType {
    HOLDERTYPE_NONE,
    HOLDERTYPE_WATERING_CAN,
    HOLDERTYPE_FERTILIZER,
    HOLDERTYPE_BUG_SPRAY,
    HOLDERTYPE_PHONOGRAPH,
    HOLDERTYPE_GLOVE,
    HOLDERTYPE_CHOCOLATE,
    HOLDERTYPE_TREE_FOOD,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum JoustGridType {
    GRID_GRASS = 0,
    GRID_WATER = 1,
    GRID_HIGH_GROUND = 2,
    GRID_ROOF = 3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum LawnMowerType {
    LAWNMOWER_NORMAL = 0,
    LAWNMOWER_POOL_CLEANER = 1,
    LAWNMOWER_ROOF_CLEANER = 2,
    LAWNMOWER_RAKE = 3,
    LAWNMOWER_SUPER_MOWER = 4,
    LAWNMOWER_VERSUS = 5,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GridSquareType {
    GRIDSQUARE_NONE = 0,
    GRIDSQUARE_GRASS = 1,
    GRIDSQUARE_DIRT = 2,
    GRIDSQUARE_POOL = 3,
    GRIDSQUARE_HIGH_GROUND = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum HelmType {
    HELMTYPE_NONE = 0,
    HELMTYPE_TRAFFIC_CONE = 1,
    HELMTYPE_PAIL = 2,
    HELMTYPE_FOOTBALL = 3,
    HELMTYPE_DIGGER = 4,
    HELMTYPE_REDEYES = 5,
    HELMTYPE_HEADBAND = 6,
    HELMTYPE_BOBSLED = 7,
    HELMTYPE_WALLNUT = 8,
    HELMTYPE_TALLNUT = 9,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum LevelFlags {
    LEVEL_FLAG_SIX_ARM_PEN = 0,
    LEVEL_FLAG_GRAVE_STONES = 1,
    LEVEL_FLAG_POOL = 2,
    LEVEL_FLAG_ROOF = 3,
    LEVEL_FLAG_FOG = 4,
    LEVEL_FLAG_SLOT_MACHINE = 5,
    LEVEL_FLAG_SEED_CHOOSER = 6,
    LEVEL_FLAG_ONLY_LILYPAD = 7,
    LEVEL_FLAG_BRAIN_BOWLING = 8,
    LEVEL_FLAG_PLANTS_VS_PLANTS = 9,
    LEVEL_FLAG_WALLNUT_BOWLING = 10,
    LEVEL_FLAG_SLOT_MACHINE_ADVENTURE = 11,
    LEVEL_FLAG_ZOMBIE_NIMBLE = 12,
    LEVEL_FLAG_LITTLE_TROUBLE = 13,
    LEVEL_FLAG_PORTAL_COMBAT = 14,
    LEVEL_FLAG_COLUMN = 15,
    LEVEL_FLAG_RAINING_SEEDS = 16,
    LEVEL_FLAG_POGO_PARTY = 17,
    LEVEL_FLAG_PUZZLE_MODE = 18,
    LEVEL_FLAG_SCARY_POTTER = 19,
    LEVEL_FLAG_BOBSLED_BONANZA = 20,
    LEVEL_FLAG_WALLNUT_BOWLING_2 = 21,
    LEVEL_FLAG_RAINING_SEEDS_2 = 22,
    LEVEL_FLAG_HELP_ZA_WALLNUT = 23,
    LEVEL_FLAG_SQUISH_ZOMBIE = 24,
    LEVEL_FLAG_TWO_PLAYER_VERSUS = 25,
    LEVEL_FLAG_TWO_PLAYER_COOP = 26,
    LEVEL_FLAG_WAR_AND_PEAS = 27,
    LEVEL_FLAG_ZOMBIE_QUICK = 28,
    LEVEL_FLAG_INVISIBLE_ZOMBIE = 29,
    LEVEL_FLAG_I_ZOMBIE = 30,
    LEVEL_FLAG_ZOMBIES_ON_THE_ROCKS = 31,
    NUM_LEVEL_FLAGS,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum MowerState {
    MOWER_OFF_LAWN,
    MOWER_READY,
    MOWER_TRIGGERED,
    MOWER_TRIGGERED_SQUASHED,
    MOWER_PASSED_ZOMBIE,
    MOWER_IN_GRAVE,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ParticleAlignType {
    PARTICLE_ALIGN_NONE,
    PARTICLE_ALIGN_SPACE,
    PARTICLE_ALIGN_PIXEL,
    PARTICLE_ALIGN_PIXEL_FULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ParticleType {
    PARTICLE_PEA_SPLASH = 0,
    PARTICLE_PEA_SPLASH_SMALL = 1,
    PARTICLE_SNOW_SPLASH = 2,
    PARTICLE_SNOW_SPLASH_SMALL = 3,
    PARTICLE_FIRE_SPLASH = 4,
    PARTICLE_FIRE_SPLASH_SMALL = 5,
    PARTICLE_SLEEPING = 6,
    PARTICLE_WOOD_PICKAXE = 7,
    PARTICLE_SCREEN_FLASH = 8,
    PARTICLE_WANING_SUN = 9,
    PARTICLE_SEED_PACKET = 10,
    PARTICLE_ZOMBIE_HEAD = 11,
    PARTICLE_ZOMBIE_ARM = 12,
    PARTICLE_BUTTON_GLOW = 13,
    PARTICLE_SCARY_POT_SPLIT = 14,
    PARTICLE_GRAVE_BUSTER = 15,
    PARTICLE_CHERRY_SPLASH = 16,
    PARTICLE_POTATO_MINE = 17,
    PARTICLE_POTATO_MINE_HEAD = 18,
    PARTICLE_SQUASH = 19,
    PARTICLE_WATER_SPLASH = 20,
    PARTICLE_DIGGER_DIRT = 21,
    PARTICLE_ZOMBIE_DIGGER_HEAD = 22,
    PARTICLE_DOOM = 23,
    PARTICLE_BALLOON_POP = 24,
    PARTICLE_COBCANNON_SPARKLE = 25,
    PARTICLE_MOWER_SPARKLE = 26,
    PARTICLE_BOSS_SPARKLE = 27,
    PARTICLE_BOSS_SPARKLE_2 = 28,
    PARTICLE_TRAIL_SMOKE = 29,
    PARTICLE_SNOW_PEA_SPLASH = 30,
    PARTICLE_PEA_SPLASH_SMALL_2 = 31,
    PARTICLE_ZOMBIE_SQUASH = 32,
    PARTICLE_TANGLEKELP_BUBBLE = 33,
    PARTICLE_JALAPENO_FIRE = 34,
    PARTICLE_FIRE_PEA_SPLASH = 35,
    PARTICLE_SUN_RISE = 36,
    PARTICLE_SUN_STREAK = 37,
    PARTICLE_PORTAL_CIRCLE = 38,
    PARTICLE_BOSS_BALLOON = 39,
    PARTICLE_BOSS_BALLOON_BALLOON = 40,
    PARTICLE_BOSS_BALLOON_BASKET = 41,
    PARTICLE_BOSS_HEAD_ON_FIRE = 42,
    PARTICLE_DIGGER_DIRT_SMALL = 43,
    PARTICLE_POOL_SPARKLE = 44,
    PARTICLE_PLANTING = 45,
    PARTICLE_CHOCOLATE_SPLASH = 46,
    PARTICLE_PRESENT_SPLASH = 47,
    PARTICLE_PRESENT_PICKUP = 48,
    PARTICLE_BOSS_DRIVER_DEATH = 49,
    PARTICLE_PLANT_GLOW = 50,
    PARTICLE_ZOMBONUS = 51,
    PARTICLE_BEGHOULED_DRAG = 52,
    PARTICLE_GRAVEL_MARIGOLD = 53,
    PARTICLE_HAMMER = 54,
    PARTICLE_BUNGEE_BLING = 55,
    PARTICLE_LANTERN = 56,
    PARTICLE_UMBRELLA = 57,
    PARTICLE_GLOW_VERTICAL = 58,
    PARTICLE_MAGNETSHROOM = 59,
    NUM_PARTICLE_TYPES,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum PlantWeaponType {
    WEAPON_PEASHOOTER = 0,
    WEAPON_SNOWPEA = 1,
    WEAPON_CABBAGE = 2,
    WEAPON_MELON = 3,
    WEAPON_WINTERMELON = 4,
    WEAPON_COB_CANNON = 5,
    WEAPON_BUTTER = 6,
    WEAPON_KERNEL = 7,
    WEAPON_SPIKE = 8,
    WEAPON_SPIKEROCK = 9,
    WEAPON_PUFF = 10,
    WEAPON_FUME = 11,
    WEAPON_CACTUS = 12,
    WEAPON_BLOVER = 13,
    WEAPON_STAR = 14,
    WEAPON_GARLIC = 15,
    WEAPON_FIREBALL = 16,
    WEAPON_ICE = 17,
    WEAPON_FIRE = 18,
    WEAPON_BOBSLED = 19,
    NUM_WEAPON_TYPES,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ProjectileType {
    PROJECTILE_PEA = 0,
    PROJECTILE_SNOWPEA = 1,
    PROJECTILE_CABBAGE = 2,
    PROJECTILE_MELON = 3,
    PROJECTILE_WINTERMELON = 4,
    PROJECTILE_COB = 5,
    PROJECTILE_BUTTER = 6,
    PROJECTILE_KERNEL = 7,
    PROJECTILE_SPIKE = 8,
    PROJECTILE_SPIKEROCK = 9,
    PROJECTILE_PUFF = 10,
    PROJECTILE_FUME = 11,
    PROJECTILE_CACTUS = 12,
    PROJECTILE_BLOVER = 13,
    PROJECTILE_STAR = 14,
    PROJECTILE_GARLIC = 15,
    PROJECTILE_FIREBALL = 16,
    PROJECTILE_ICE = 17,
    PROJECTILE_FIRE = 18,
    PROJECTILE_BOBSLED = 19,
    PROJECTILE_FIREBALL_BOSS = 20,
    NUM_PROJECTILE_TYPES,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ReanimationType {
    REANIM_NONE = u32::MAX,
    REANIM_LOADBAR_SPROUT = 0,
    REANIM_LOADBAR_ZOMBIEHEAD,
    REANIM_SODROLL,
    REANIM_FINAL_WAVE,
    REANIM_PEASHOOTER,
    REANIM_WALLNUT,
    REANIM_LILYPAD,
    REANIM_SUNFLOWER,
    REANIM_LAWNMOWER,
    REANIM_READYSETPLANT,
    REANIM_CHERRYBOMB,
    REANIM_SQUASH,
    REANIM_DOOMSHROOM,
    REANIM_SNOWPEA,
    REANIM_REPEATER,
    REANIM_SUNSHROOM,
    REANIM_TALLNUT,
    REANIM_FUMESHROOM,
    REANIM_PUFFSHROOM,
    REANIM_HYPNOSHROOM,
    REANIM_CHOMPER,
    REANIM_ZOMBIE,
    REANIM_SUN,
    REANIM_POTATOMINE,
    REANIM_SPIKEWEED,
    REANIM_SPIKEROCK,
    REANIM_THREEPEATER,
    REANIM_MARIGOLD,
    REANIM_ICESHROOM,
    REANIM_ZOMBIE_FOOTBALL,
    REANIM_ZOMBIE_NEWSPAPER,
    REANIM_ZOMBIE_ZAMBONI,
    REANIM_SPLASH,
    REANIM_JALAPENO,
    REANIM_JALAPENO_FIRE,
    REANIM_COIN_SILVER,
    REANIM_ZOMBIE_CHARRED,
    REANIM_ZOMBIE_CHARRED_IMP,
    REANIM_ZOMBIE_CHARRED_DIGGER,
    REANIM_ZOMBIE_CHARRED_ZAMBONI,
    REANIM_ZOMBIE_CHARRED_CATAPULT,
    REANIM_ZOMBIE_CHARRED_GARGANTUAR,
    REANIM_SCRAREYSHROOM,
    REANIM_PUMPKIN,
    REANIM_PLANTERN,
    REANIM_TORCHWOOD,
    REANIM_SPLITPEA,
    REANIM_SEASHROOM,
    REANIM_BLOVER,
    REANIM_FLOWER_POT,
    REANIM_CACTUS,
    REANIM_DANCER,
    REANIM_TANGLEKELP,
    REANIM_STARFRUIT,
    REANIM_POLEVAULTER,
    REANIM_BALLOON,
    REANIM_GARGANTUAR,
    REANIM_IMP,
    REANIM_DIGGER,
    REANIM_DIGGER_DIRT,
    REANIM_ZOMBIE_DOLPHINRIDER,
    REANIM_POGO,
    REANIM_BACKUP_DANCER,
    REANIM_BOBSLED,
    REANIM_JACKINTHEBOX,
    REANIM_SNORKEL,
    REANIM_BUNGEE,
    REANIM_CATAPULT,
    REANIM_LADDER,
    REANIM_PUFF,
    REANIM_SLEEPING,
    REANIM_GRAVE_BUSTER,
    REANIM_ZOMBIES_WON,
    REANIM_MAGNETSHROOM,
    REANIM_BOSS,
    REANIM_CABBAGEPULT,
    REANIM_KERNELPULT,
    REANIM_MELONPULT,
    REANIM_COFFEEBEAN,
    REANIM_UMBRELLALEAF,
    REANIM_GATLINGPEA,
    REANIM_CATTAIL,
    REANIM_GLOOMSHROOM,
    REANIM_BOSS_ICEBALL,
    REANIM_BOSS_FIREBALL,
    REANIM_COBCANNON,
    REANIM_GARLIC,
    REANIM_GOLD_MAGNET,
    REANIM_WINTER_MELON,
    REANIM_TWIN_SUNFLOWER,
    REANIM_POOL_CLEANER,
    REANIM_ROOF_CLEANER,
    REANIM_FIRE_PEA,
    REANIM_IMITATER,
    REANIM_YETI,
    REANIM_BOSS_DRIVER,
    REANIM_LAWN_MOWERED_ZOMBIE,
    REANIM_CRAZY_DAVE,
    REANIM_TEXT_FADE_ON,
    REANIM_HAMMER,
    REANIM_SLOT_MACHINE_HANDLE,
    REANIM_CREDITS_FOOTBALL,
    REANIM_CREDITS_JACKBOX,
    REANIM_SELECTOR_SCREEN,
    REANIM_PORTAL_CIRCLE,
    REANIM_PORTAL_SQUARE,
    REANIM_ZENGARDEN_SPROUT,
    REANIM_ZENGARDEN_WATERINGCAN,
    REANIM_ZENGARDEN_FERTILIZER,
    REANIM_ZENGARDEN_BUGSPRAY,
    REANIM_ZENGARDEN_PHONOGRAPH,
    REANIM_DIAMOND,
    REANIM_ZOMBIE_HAND,
    REANIM_STINKY,
    REANIM_RAKE,
    REANIM_RAIN_CIRCLE,
    REANIM_RAIN_SPLASH,
    REANIM_ZOMBIE_SURPRISE,
    REANIM_COIN_GOLD,
    REANIM_TREEOFWISDOM,
    REANIM_TREEOFWISDOM_CLOUDS,
    REANIM_TREEOFWISDOM_TREEFOOD,
    REANIM_CREDITS_MAIN,
    REANIM_CREDITS_MAIN2,
    REANIM_CREDITS_MAIN3,
    REANIM_ZOMBIE_CREDITS_DANCE,
    REANIM_CREDITS_STAGE,
    REANIM_CREDITS_BIGBRAIN,
    REANIM_CREDITS_FLOWER_PETALS,
    REANIM_CREDITS_INFANTRY,
    REANIM_CREDITS_THROAT,
    REANIM_CREDITS_CRAZYDAVE,
    REANIM_CREDITS_BOSSDANCE,
    REANIM_ZOMBIE_CREDITS_SCREEN_DOOR,
    REANIM_ZOMBIE_CREDITS_CONEHEAD,
    REANIM_CREDITS_ZOMBIEARMY1,
    REANIM_CREDITS_ZOMBIEARMY2,
    REANIM_CREDITS_TOMBSTONES,
    REANIM_CREDITS_SOLARPOWER,
    REANIM_CREDITS_ANYHOUR,
    REANIM_CREDITS_WEARETHEUNDEAD,
    REANIM_CREDITS_DISCOLIGHTS,
    REANIM_FLAG,
    REANIM_ZOMBATAR_HEAD,
    NUM_REANIMS,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum RenderLayer {
    RENDER_LAYER_GRAVE_STONE = 301000,
    RENDER_LAYER_PLANT = 302000,
    RENDER_LAYER_ZOMBIE = 303000,
    RENDER_LAYER_BOSS = 304000,
    RENDER_LAYER_PROJECTILE = 305000,
    RENDER_LAYER_LAWN_MOWER = 306000,
    RENDER_LAYER_PARTICLE = 307000,
    RENDER_LAYER_TOP = 400000,
    RENDER_LAYER_FOG = 500000,
    RENDER_LAYER_COIN_BANK = 600000,
    RENDER_LAYER_UI_TOP = 700000,
    RENDER_LAYER_ABOVE_UI = 800000,
    RENDER_LAYER_SCREEN_FADE = 900000,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum RenderObjectType {
    RENDER_ITEM_COIN,
    RENDER_ITEM_PROJECTILE,
    RENDER_ITEM_ZOMBIE,
    RENDER_ITEM_ZOMBIE_SHADOW,
    RENDER_ITEM_ZOMBIE_BUNGEE_TARGET,
    RENDER_ITEM_PLANT,
    RENDER_ITEM_PLANT_OVERLAY,
    RENDER_ITEM_PLANT_MAGNET_ITEMS,
    RENDER_ITEM_CURSOR_PREVIEW,
    RENDER_ITEM_PARTICLE,
    RENDER_ITEM_REANIMATION,
    RENDER_ITEM_ICE,
    RENDER_ITEM_TOP_UI,
    RENDER_ITEM_FOG,
    RENDER_ITEM_STORM,
    RENDER_ITEM_BOTTOM_UI,
    RENDER_ITEM_BACKDROP,
    RENDER_ITEM_DOOR_MASK,
    RENDER_ITEM_COIN_BANK,
    RENDER_ITEM_PROJECTILE_SHADOW,
    RENDER_ITEM_MOWER,
    RENDER_ITEM_SCREEN_FADE,
    RENDER_ITEM_BOSS_PART,
    RENDER_ITEM_GRID_ITEM,
    RENDER_ITEM_GRID_ITEM_OVERLAY,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ScaryPotType {
    SCARYPOT_NONE = 0,
    SCARYPOT_SEED = 1,
    SCARYPOT_ZOMBIE = 2,
    SCARYPOT_SUN = 3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum SeedChooserState {
    CHOOSE_NORMAL = 0,
    CHOOSE_VIEW_LAWN = 1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum SeedType {
    SEED_PEASHOOTER = 0,
    SEED_SUNFLOWER = 1,
    SEED_CHERRYBOMB = 2,
    SEED_WALLNUT = 3,
    SEED_POTATOMINE = 4,
    SEED_SNOWPEA = 5,
    SEED_CHOMPER = 6,
    SEED_REPEATER = 7,
    SEED_PUFFSHROOM = 8,
    SEED_SUNSHROOM = 9,
    SEED_FUMESHROOM = 10,
    SEED_GRAVEBUSTER = 11,
    SEED_HYPNOSHROOM = 12,
    SEED_SCAREDYSHROOM = 13,
    SEED_ICESHROOM = 14,
    SEED_DOOMSHROOM = 15,
    SEED_LILYPAD = 16,
    SEED_SQUASH = 17,
    SEED_THREEPEATER = 18,
    SEED_TANGLEKELP = 19,
    SEED_JALAPENO = 20,
    SEED_SPIKEWEED = 21,
    SEED_TORCHWOOD = 22,
    SEED_TALLNUT = 23,
    SEED_SEASHROOM = 24,
    SEED_PLANTERN = 25,
    SEED_CACTUS = 26,
    SEED_BLOVER = 27,
    SEED_SPLITPEA = 28,
    SEED_STARFRUIT = 29,
    SEED_PUMPKINSHELL = 30,
    SEED_MAGNETSHROOM = 31,
    SEED_CABBAGEPULT = 32,
    SEED_FLOWERPOT = 33,
    SEED_KERNELPULT = 34,
    SEED_INSTANT_COFFEE = 35,
    SEED_GARLIC = 36,
    SEED_UMBRELLA = 37,
    SEED_MARIGOLD = 38,
    SEED_MELONPULT = 39,
    SEED_GATLINGPEA = 40,
    SEED_TWINSUNFLOWER = 41,
    SEED_GLOOMSHROOM = 42,
    SEED_CATTAIL = 43,
    SEED_WINTERMELON = 44,
    SEED_GOLD_MAGNET = 45,
    SEED_SPIKEROCK = 46,
    SEED_COBCANNON = 47,
    SEED_IMITATER = 48,
    SEED_EXPLODE_O_NUT,
    SEED_GIANT_WALLNUT,
    SEED_SPROUT,
    SEED_LEFTPEATER,
    NUM_SEED_TYPES,
    SEED_BEGHOULED_BUTTON_SHUFFLE,
    SEED_BEGHOULED_BUTTON_CRATER,
    SEED_SLOT_MACHINE_SUN,
    SEED_SLOT_MACHINE_DIAMOND,
    SEED_ZOMBIQUARIUM_SNORKLE,
    SEED_ZOMBIQUARIUM_TROPHY,
    SEED_ZOMBIE_NORMAL,
    SEED_ZOMBIE_TRAFFIC_CONE,
    SEED_ZOMBIE_POLEVAULTER,
    SEED_ZOMBIE_PAIL,
    SEED_ZOMBIE_LADDER,
    SEED_ZOMBIE_DIGGER,
    SEED_ZOMBIE_BUNGEE,
    SEED_ZOMBIE_FOOTBALL,
    SEED_ZOMBIE_BALLOON,
    SEED_ZOMBIE_SCREEN_DOOR,
    SEED_ZOMBONI,
    SEED_ZOMBIE_POGO,
    SEED_ZOMBIE_DANCER,
    SEED_ZOMBIE_GARGANTUAR,
    SEED_ZOMBIE_IMP,
    SEED_NONE = -1,
}
pub const NUM_SEEDS_IN_CHOOSER: i32 = 49;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ShieldType {
    SHIELDTYPE_NONE,
    SHIELDTYPE_DOOR,
    SHIELDTYPE_NEWSPAPER,
    SHIELDTYPE_LADDER,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum StoreItem {
    STORE_ITEM_PLANT_GATLINGPEA,
    STORE_ITEM_PLANT_TWINSUNFLOWER,
    STORE_ITEM_PLANT_GLOOMSHROOM,
    STORE_ITEM_PLANT_CATTAIL,
    STORE_ITEM_PLANT_WINTERMELON,
    STORE_ITEM_PLANT_GOLD_MAGNET,
    STORE_ITEM_PLANT_SPIKEROCK,
    STORE_ITEM_PLANT_COBCANNON,
    STORE_ITEM_PLANT_IMITATER,
    STORE_ITEM_BONUS_LAWN_MOWER,
    STORE_ITEM_POTTED_MARIGOLD_1,
    STORE_ITEM_POTTED_MARIGOLD_2,
    STORE_ITEM_POTTED_MARIGOLD_3,
    STORE_ITEM_GOLD_WATERINGCAN,
    STORE_ITEM_FERTILIZER,
    STORE_ITEM_BUG_SPRAY,
    STORE_ITEM_PHONOGRAPH,
    STORE_ITEM_GARDENING_GLOVE,
    STORE_ITEM_MUSHROOM_GARDEN,
    STORE_ITEM_WHEEL_BARROW,
    STORE_ITEM_STINKY_THE_SNAIL,
    STORE_ITEM_PACKET_UPGRADE,
    STORE_ITEM_POOL_CLEANER,
    STORE_ITEM_ROOF_CLEANER,
    STORE_ITEM_RAKE,
    STORE_ITEM_AQUARIUM_GARDEN,
    STORE_ITEM_CHOCOLATE,
    STORE_ITEM_TREE_OF_WISDOM,
    STORE_ITEM_TREE_FOOD,
    STORE_ITEM_FIRSTAID,
    STORE_ITEM_PVZ,
}

pub const STORE_ITEM_INVALID: i32 = -1;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum StorePages {
    STORE_PAGE_SLOT_UPGRADES = 0,
    STORE_PAGE_PLANT_UPGRADES = 1,
    STORE_PAGE_ZEN1 = 2,
    STORE_PAGE_ZEN2 = 3,
    NUM_STORE_PAGES = 4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum TodCurves {
    CURVE_CONSTANT,
    CURVE_LINEAR,
    CURVE_EASE_IN,
    CURVE_EASE_OUT,
    CURVE_EASE_IN_OUT,
    CURVE_EASE_IN_OUT_WEAK,
    CURVE_FAST_IN_OUT,
    CURVE_FAST_IN_OUT_WEAK,
    CURVE_WEAK_FAST_IN_OUT,
    CURVE_BOUNCE,
    CURVE_BOUNCE_FAST_MIDDLE,
    CURVE_BOUNCE_SLOW_MIDDLE,
    CURVE_SIN_WAVE,
    CURVE_EASE_SIN_WAVE,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum TrialType {
    TRIALTYPE_NONE,
    TRIALTYPE_STAGELOCKED,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum TutorialState {
    TUTORIAL_OFF = 0,
    TUTORIAL_LEVEL_1_PICK_UP_PEASHOOTER = 1,
    TUTORIAL_LEVEL_1_PLANT_PEASHOOTER = 2,
    TUTORIAL_LEVEL_1_REFRESH_PEASHOOTER = 3,
    TUTORIAL_LEVEL_1_COMPLETED = 4,
    TUTORIAL_LEVEL_2_PICK_UP_SUNFLOWER = 5,
    TUTORIAL_LEVEL_2_PLANT_SUNFLOWER = 6,
    TUTORIAL_LEVEL_2_REFRESH_SUNFLOWER = 7,
    TUTORIAL_LEVEL_2_COMPLETED = 8,
    TUTORIAL_MORESUN_PICK_UP_SUNFLOWER = 9,
    TUTORIAL_MORESUN_PLANT_SUNFLOWER = 10,
    TUTORIAL_MORESUN_REFRESH_SUNFLOWER = 11,
    TUTORIAL_MORESUN_COMPLETED = 12,
    TUTORIAL_SLOT_MACHINE_PULL = 13,
    TUTORIAL_SLOT_MACHINE_COMPLETED = 14,
    TUTORIAL_SHOVEL_PICKUP = 15,
    TUTORIAL_SHOVEL_DIG = 16,
    TUTORIAL_SHOVEL_KEEP_DIGGING = 17,
    TUTORIAL_SHOVEL_COMPLETED = 18,
    TUTORIAL_ZOMBIQUARIUM_BUY_SNORKEL = 19,
    TUTORIAL_ZOMBIQUARIUM_BOUGHT_SNORKEL = 20,
    TUTORIAL_ZOMBIQUARIUM_CLICK_TROPHY = 21,
    TUTORIAL_ZEN_GARDEN_PICKUP_WATER = 22,
    TUTORIAL_ZEN_GARDEN_WATER_PLANT = 23,
    TUTORIAL_ZEN_GARDEN_KEEP_WATERING = 24,
    TUTORIAL_ZEN_GARDEN_VISIT_STORE = 25,
    TUTORIAL_ZEN_GARDEN_FERTILIZE_PLANTS = 26,
    TUTORIAL_ZEN_GARDEN_COMPLETED = 27,
    TUTORIAL_WHACK_A_ZOMBIE_BEFORE_PICK_SEED = 28,
    TUTORIAL_WHACK_A_ZOMBIE_PICK_SEED = 29,
    TUTORIAL_WHACK_A_ZOMBIE_COMPLETED = 30,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum UnlockingState {
    UNLOCK_OFF,
    UNLOCK_SHAKING,
    UNLOCK_FADING,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ZombieHeight {
    HEIGHT_ZOMBIE_NORMAL = 0,
    HEIGHT_IN_TO_POOL = 1,
    HEIGHT_OUT_OF_POOL = 2,
    HEIGHT_DRAGGED_UNDER = 3,
    HEIGHT_UP_TO_HIGH_GROUND = 4,
    HEIGHT_DOWN_OFF_HIGH_GROUND = 5,
    HEIGHT_UP_LADDER = 6,
    HEIGHT_FALLING = 7,
    HEIGHT_IN_TO_CHIMNEY = 8,
    HEIGHT_GETTING_BUNGEE_DROPPED = 9,
    HEIGHT_ZOMBIQUARIUM = 10,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ZombiePhase {
    PHASE_ZOMBIE_NORMAL,
    PHASE_ZOMBIE_DYING,
    PHASE_ZOMBIE_BURNED,
    PHASE_ZOMBIE_MOWERED,
    PHASE_BUNGEE_DIVING,
    PHASE_BUNGEE_DIVING_SCREAMING,
    PHASE_BUNGEE_AT_BOTTOM,
    PHASE_BUNGEE_GRABBING,
    PHASE_BUNGEE_RISING,
    PHASE_BUNGEE_HIT_OUCHY,
    PHASE_BUNGEE_CUTSCENE,
    PHASE_POLEVAULTER_PRE_VAULT,
    PHASE_POLEVAULTER_IN_VAULT,
    PHASE_POLEVAULTER_POST_VAULT,
    PHASE_RISING_FROM_GRAVE,
    PHASE_JACK_IN_THE_BOX_RUNNING,
    PHASE_JACK_IN_THE_BOX_POPPING,
    PHASE_BOBSLED_SLIDING,
    PHASE_BOBSLED_BOARDING,
    PHASE_BOBSLED_CRASHING,
    PHASE_POGO_BOUNCING,
    PHASE_POGO_HIGH_BOUNCE_1,
    PHASE_POGO_HIGH_BOUNCE_2,
    PHASE_POGO_HIGH_BOUNCE_3,
    PHASE_POGO_HIGH_BOUNCE_4,
    PHASE_POGO_HIGH_BOUNCE_5,
    PHASE_POGO_HIGH_BOUNCE_6,
    PHASE_POGO_FORWARD_BOUNCE_2,
    PHASE_POGO_FORWARD_BOUNCE_7,
    PHASE_NEWSPAPER_READING,
    PHASE_NEWSPAPER_MADDENING,
    PHASE_NEWSPAPER_MAD,
    PHASE_DIGGER_TUNNELING,
    PHASE_DIGGER_RISING,
    PHASE_DIGGER_TUNNELING_PAUSE_WITHOUT_AXE,
    PHASE_DIGGER_RISE_WITHOUT_AXE,
    PHASE_DIGGER_STUNNED,
    PHASE_DIGGER_WALKING,
    PHASE_DIGGER_WALKING_WITHOUT_AXE,
    PHASE_DIGGER_CUTSCENE,
    PHASE_DANCER_DANCING_IN,
    PHASE_DANCER_SNAPPING_FINGERS,
    PHASE_DANCER_SNAPPING_FINGERS_WITH_LIGHT,
    PHASE_DANCER_SNAPPING_FINGERS_HOLD,
    PHASE_DANCER_DANCING_LEFT,
    PHASE_DANCER_WALK_TO_RAISE,
    PHASE_DANCER_RAISE_LEFT_1,
    PHASE_DANCER_RAISE_LEFT_2,
    PHASE_DANCER_RISING,
    PHASE_DOLPHIN_WALKING,
    PHASE_DOLPHIN_INTO_POOL,
    PHASE_DOLPHIN_RIDING,
    PHASE_DOLPHIN_IN_JUMP,
    PHASE_DOLPHIN_WALKING_IN_POOL,
    PHASE_DOLPHIN_WALKING_WITHOUT_DOLPHIN,
    PHASE_SNORKEL_WALKING,
    PHASE_SNORKEL_INTO_POOL,
    PHASE_SNORKEL_WALKING_IN_POOL,
    PHASE_SNORKEL_UP_TO_EAT,
    PHASE_SNORKEL_EATING_IN_POOL,
    PHASE_SNORKEL_DOWN_FROM_EAT,
    PHASE_ZOMBIQUARIUM_ACCEL,
    PHASE_ZOMBIQUARIUM_DRIFT,
    PHASE_ZOMBIQUARIUM_BACK_AND_FORTH,
    PHASE_ZOMBIQUARIUM_BITE,
    PHASE_CATAPULT_LAUNCHING,
    PHASE_CATAPULT_RELOADING,
    PHASE_GARGANTUAR_THROWING,
    PHASE_GARGANTUAR_SMASHING,
    PHASE_IMP_GETTING_THROWN,
    PHASE_IMP_LANDING,
    PHASE_BALLOON_FLYING,
    PHASE_BALLOON_POPPING,
    PHASE_BALLOON_WALKING,
    PHASE_LADDER_CARRYING,
    PHASE_LADDER_PLACING,
    PHASE_BOSS_ENTER,
    PHASE_BOSS_IDLE,
    PHASE_BOSS_SPAWNING,
    PHASE_BOSS_STOMPING,
    PHASE_BOSS_BUNGEES_ENTER,
    PHASE_BOSS_BUNGEES_DROP,
    PHASE_BOSS_BUNGEES_LEAVE,
    PHASE_BOSS_DROP_RV,
    PHASE_BOSS_HEAD_ENTER,
    PHASE_BOSS_HEAD_IDLE_BEFORE_SPIT,
    PHASE_BOSS_HEAD_IDLE_AFTER_SPIT,
    PHASE_BOSS_HEAD_SPIT,
    PHASE_BOSS_HEAD_LEAVE,
    PHASE_YETI_RUNNING,
    PHASE_SQUASH_PRE_LAUNCH,
    PHASE_SQUASH_RISING,
    PHASE_SQUASH_FALLING,
    PHASE_SQUASH_DONE_FALLING,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ZombieType {
    ZOMBIE_INVALID = -1,
    ZOMBIE_NORMAL,
    ZOMBIE_FLAG,
    ZOMBIE_TRAFFIC_CONE,
    ZOMBIE_POLEVAULTER,
    ZOMBIE_PAIL,
    ZOMBIE_NEWSPAPER,
    ZOMBIE_DOOR,
    ZOMBIE_FOOTBALL,
    ZOMBIE_DANCER,
    ZOMBIE_BACKUP_DANCER,
    ZOMBIE_DUCKY_TUBE,
    ZOMBIE_SNORKEL,
    ZOMBIE_ZAMBONI,
    ZOMBIE_BOBSLED,
    ZOMBIE_DOLPHIN_RIDER,
    ZOMBIE_JACK_IN_THE_BOX,
    ZOMBIE_BALLOON,
    ZOMBIE_DIGGER,
    ZOMBIE_POGO,
    ZOMBIE_YETI,
    ZOMBIE_BUNGEE,
    ZOMBIE_LADDER,
    ZOMBIE_CATAPULT,
    ZOMBIE_GARGANTUAR,
    ZOMBIE_IMP,
    ZOMBIE_BOSS,
    ZOMBIE_PEA_HEAD,
    ZOMBIE_WALLNUT_HEAD,
    ZOMBIE_JALAPENO_HEAD,
    ZOMBIE_GATLING_HEAD,
    ZOMBIE_SQUASH_HEAD,
    ZOMBIE_TALLNUT_HEAD,
    ZOMBIE_REDEYE_GARGANTUAR,
    NUM_ZOMBIE_TYPES,
    ZOMBIE_CACHED_POLEVAULTER_WITH_POLE,
    NUM_CACHED_ZOMBIE_TYPES,
}

// ID type aliases (matching the enum-based ID pattern in C++)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum AttachmentID {
    ATTACHMENTID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum CoinID {
    COINID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ParticleID {
    PARTICLEID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ParticleEmitterID {
    PARTICLEEMITTERID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ParticleSystemID {
    PARTICLESYSTEMID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum PlantID {
    PLANTID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ReanimationID {
    REANIMATIONID_NULL,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ZombieID {
    ZOMBIEID_NULL,
}
